services:
  - type: web
    name: swapit
    runtime: php
    plan: free
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: chmod +x render-start.sh && ./render-start.sh
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: RAILWAY_DB_HOST
        sync: false
      - key: RAILWAY_DB_PORT
        sync: false
      - key: RAILWAY_DB_NAME
        sync: false
      - key: RAILWAY_DB_USER
        sync: false
      - key: RAILWAY_DB_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
