services:
  - type: web
    name: swapit
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: swapit-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false

databases:
  - name: swapit-db
    databaseName: swapit_db_99av
    user: swapit_user
    plan: free
