services:
  - type: web
    name: swapit
    runtime: php
    env: php
    buildCommand: bash render-build.sh
    startCommand: bash render-start.sh
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: SI2025
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false

databases:
  - name: swapit-db
    databaseName: SI2025
    user: swapit_user
